[package]
name = "scope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
tui = "0.19.0"
crossterm = "0.25.0"
chrono = "0.4.23"
serde = "1.0"
serde_yaml = "0.9"
rand = "0.8.5"
clap = { version = "4.1.9", features = ["derive"] }
terminal-light = "1.1.1"
